 name: perturbation-test
 on: [push]
 jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repot_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Workflow goes here
          pip install -r requirements.txt
          python run_perturbation_test.py

          # Report the diffs
          echo "## Workspace vs. Main" > report.md
          git fetch --prune
          dvc metrics diff --targets test_score.json --show-md >> report.md

          # printout failure modes
          echo "## Failure modes" >> report.md
          cat failure_modes.txt >> report.md

          # Sent it
          cml-send-comment report.md